# render.yaml
services:
  - type: web
    name: postgres-db
    env: docker
    plan: free
    repo: https://github.com/Lucario119/energy-bills-data-challenge
    branch: master
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: password
      - key: DB_NAME
        value: energy_bills
      - key: DB_HOST
        value: localhost
